version: '3.8'

services:
  nestjs-app:
    image: node:18
    container_name: recipe-api
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/mydb?schema=public
      - API_PORT=8080
    command: bash -c "npm i -g npm@latest && npm install --legacy-peer-deps && npm run migrate && npm run start:dev"
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
